name: itrace_247
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+9

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.8
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.5.0
  pin_code_fields: ^7.4.0
  flutter_svg: ^1.1.4
  image_picker: ^0.8.5+3
  flutter_screenutil: ^5.5.4
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  get_it: ^7.2.0
  cached_network_image: ^3.2.2
  flutter_launcher_icons: ^0.10.0
  intl_utils: ^2.7.0
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15

#================config splash screen========================
flutter_native_splash:
# flutter pub run flutter_native_splash:create
  background_image: "assets/images/img_splash_screen.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_disable_fullscreen: true

flutter_icons:
# flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_intl:
  enabled: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter pub run build_runner build
  #flutter pub run build_runner build --delete-conflicting-outputs

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  retrofit_generator: ^4.0.3+2
  json_serializable: ^6.3.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
